// Code generated by "stringer -type UpdateMethod -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UpdateOverwrite-0]
	_ = x[UpdatePatch-1]
	_ = x[UpdateSync-2]
}

const _UpdateMethod_name = "overwritepatchsync"

var _UpdateMethod_index = [...]uint8{0, 9, 14, 18}

func (i UpdateMethod) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_UpdateMethod_index)-1 {
		return "UpdateMethod(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _UpdateMethod_name[_UpdateMethod_index[idx]:_UpdateMethod_index[idx+1]]
}
